### ISSUE TITLE
[UI] test complete, ocr / bottom sheet dialog 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS#28]
## ISSUE
- test complete, ocr / bottom sheet dialog 구현

## To-Do
- [x] ocr result 바텀시트 구현
- [x] jelly description 바텀시트 구현
- [x] 불필요한 viewModel 삭제
