### ISSUE TITLE
[FEAT] home / 서버통신 관련 API 연결

### ISSUE THREAD

**Issue by etama123** [Keyneez/Keyneez-AOS#38]
## ISSUE
- home 서버 통신하기

## To-Do
- [ ] 리사이클러뷰에 서버통신 데이터 연결
- [ ] 상세 페이지 연결하기
- [ ] 게시물 전체 조회 API 연결
- [ ] 게시물 찜 API 연결
