### ISSUE TITLE
[FEAT] signup / 회원가입 관련 서버 통신 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS#40]
## ISSUE
- signup / 회원가입 관련 서버 통신 구현

## To-Do
- [x] 유저 다날 정보 API 연결
- [x] 유저 성향, 관심사 API 연결
- [x] 유저 비밀번호 API 연결
- [x] 비밀번호 대조 API 연결
- [x] shared preference에 유저 정보 저장
