### ISSUE TITLE
[FEAT] ocr / Google ML Kit OCR 기능 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS#46]
## ISSUE
- ocr / Google ML Kit OCR 기능 구현

## To-Do
- [x] ocr guide 뷰 구현
- [ ] 카메라 권한 기능 보완
- [x] 수동 ocr 구현
- [ ] 자동 ocr 구현
- [x] id 발급 API 연결
- [ ] ocr complete 뷰 연결
