### ISSUE TITLE
[UI] home / 홈 화면 레이아웃 구현 

### ISSUE THREAD

**Issue by etama123** [Keyneez/Keyneez-AOS#7]
## ISSUE
- home / 홈 화면 레이아웃 구현 

## To-Do
- [x] tabLayout + viewPager 연결
- [x] viewPager2 어댑터 추가
- [x] recyclerView 뷰 구현
- [x] recyclerView item 추가
- [x] homeFragment 및 자식 fragment xml 파일 작성
