### ISSUE TITLE
[MOD] search / 코드 수정 및 추가

### ISSUE THREAD

**Issue by 0zlrlo** [Keyneez/Keyneez-AOS#77]
## ISSUE
- 검색 / 코드 수정 및 추가

## To-Do
- [x]  검색 결과 0개면 토스트 띄우기
- [ ] RecyclerView → ListAdapter 변경
- [ ] 검색화면에서도 좋아요 가능하게끔 수정
- [x] 엔터 누르면 검색되도록 수정
- [x] 긴 문자열 입력 시 검색 버튼 오른쪽에 문자 보이는 거 수정
- [x] 이미지버튼 background 투명하게 수정
