### ISSUE TITLE
[UI] ocr / ocr 뷰 구현

### ISSUE THREAD

**Issue by b1urrrr** [Keyneez/Keyneez-AOS#9]
## ISSUE
- ocr / ocr 뷰 구현

## To-Do
- [x] custom view 구현
- [x] 카메라 프리뷰 구현
- [x] 프레임 회전 기능 구현
- [x] 종료 버튼 구현
- [x] ocr guide 뷰 페이저 구현
- [x] ocr guide 뷰 구현
- [x] ocr complete 뷰 구현
